# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Of Ones and Zeros
email: bryan.napier.md@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A discussion of technology and software development by your host, Bryan Napier
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ofonesandzeros.com" # the base hostname & protocol for your site
twitter_username: ofonesandzeros
github_username:  ofonesandzeros
permalink:    /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

# Plugins
gems: [jekyll-paginate]
